### ISSUE TITLE
[Technical story] Setup modal view navigation

### ISSUE THREAD

**Issue by Wallart** [kelto/AstroVisor#23]

**Comment by kelto** [comment]
Should we add route ? At the moment, opening a modal does not change the state of the application (Not a new route / uri). It could help to define what require authentication to be displayed, and improve the user experience. But can be tricky to define what should be a state or not.

**Comment by Edsolat** [comment]
Understood. I'm on it. Should we use states (with $stateProvider) to make it ?

**Comment by kelto** [comment]
Well that's the question, i'm not sure it's either a good or bad idea to use the router yet.

**Comment by kelto** [comment]
I think the last commit reflect more how to use the stateProvider, could I have any input on that so that i can merge ?
