### ISSUE TITLE
[DescriptionService] Can't retrieve description

### ISSUE THREAD

**Issue by kelto** [kelto/AstroVisor#44]
Error : 
No signature of method: com.astrovisor.DescriptionService.getDescriptionsOfPlanet() is applicable for argument types: (java.lang.String, java.lang.Integer, java.lang.Integer) values: [2, 0, 10]

It work if we change the signature of the service function, removing the variable type.

**Comment by kelto** [comment]
This is the same for most services.
The params are all string. Apparently with groovy, if you set the variable type in the function header, you have to set the right parameters on the function call.

**Comment by Hunsu** [comment]
@kelto You have fixed don't you? There's commit referencing this issue.
