### ISSUE TITLE
Clean tests directory and delete duplications

### ISSUE THREAD

**Issue by Wallart** [kelto/AstroVisor#52]

**Comment by Hunsu** [comment]
Clean what? And which duplications you are talking about?

**Comment by Wallart** [comment]
We had 2 copies of DescriptionServiceSpec and UserServiceSpec in integration directory and unit directory. Grails was unable to run tests because of these duplications

**Comment by Hunsu** [comment]
Must delete the unit tests. I don't think it is the reason why grails couldn't run the tests. The files are there for a while now.

**Comment by Wallart** [comment]
Moreover, each copy was empty
