### ISSUE TITLE
Custom validator aren't supported by grails.buildTestData plugin

### ISSUE THREAD

**Issue by Wallart** [kelto/AstroVisor#53]

**Comment by Hunsu** [comment]
It's not an issue of this project.

**Comment by Wallart** [comment]
This is leading all tests to fail

**Comment by Hunsu** [comment]
Don't use the Build function for domain class that have custom validator or just give the values to the function. I still don't think that it's an issue of the project. It an issue of the plugin.

**Comment by Wallart** [comment]
To be more coherent and to make the frontend usable without stubbing I had to update the model.
An orbit is now belonging to a Planet.
For example, when you are using "Trade.build()" the process will finally test constraints for Orbit (because an Orbit belongs to a Planet and a Trade belongs to a Planet too).

**Comment by Hunsu** [comment]
Should rename the issue then.

**Comment by Wallart** [comment]
As stated on the plugin documentation, I had to give values manually
Reference : https://github.com/longwa/build-test-data/wiki/Features
