### ISSUE TITLE
Planet modal view doesn't show when planet code_name starts with a letter

### ISSUE THREAD

**Issue by Wallart** [kelto/AstroVisor#56]
"01-esrdf2", "1" are valid code_names
"X01-esrdf2", "L1" are invalid code_names

**Comment by kelto** [comment]
Well it should not show. At the moment the planet code_name is used as the id in the stub. Only the id (which is a number) should be used to select a specific planet, hence the rule for only allowing number in route.
But it's strange that a code_name with letter is working.

**Comment by Wallart** [comment]
Okay
I can see that in planet.controller.js you are planning to move http requests to a new service. I think these requests are not necessary, all data we need are already cached in the systems service. Currently you can get a planet by calling getPlanetByCodeName, but I can create a getPlanetById in this service
